### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by forfreal2** [heliomarpm/udemy-downloader-gui#218]
### Provide a description of requested docs changes

I'm getting an error like this

lecture.quality.toLowerCase is not a function
course:

how can i solve this

**Comment by madhav2348** [comment]
i am also getting same error 

`EPREPARE_DOWNLOADING: (0)
lecture.quality.toLowerCase is not a function
course: Python And Flask Demonstrations Practice Course`

**Comment by Gabe-W-J** [comment]
same here

```
EPREPARE_DOWNLOADING: (0)
lecture.quality.toLowerCase is not a function
course: PL-200:Microsoft Power Platform Functional Consultant Part 1
EBUILDING_COURSE_DATA: (0)
lecture.quality.toLowerCase is not a function
course: PL-200:Microsoft Power Platform Functional Consultant Part 1
```

**Comment by heliomarpm** [comment]
fixed in new version 1.13.3

**Comment by GeanPaul** [comment]
Currently the same error is still showing, I have downloaded version 1.13.3


![image](https://github.com/user-attachments/assets/2fa1c473-9778-4710-b1b7-6a36c130d924)
![image](https://github.com/user-attachments/assets/e3fd11ce-024e-4f22-968a-2ae282009765)
